apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: engineering-dev
        url: https://kubernetes.guestbook.svc
      - cluster: engineering-prod
        url: https://kubernetes.guestbook.svc
      - cluster: finance-preprod
        url: https://kubernetes.guestbook.svc
  template:
    metadata:
      name: '{{.cluster}}-guestbook'
    spec:
      project: se
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps
        targetRevision: HEAD
        path: guestbook
      destination:
        server: '{{.url}}'
        namespace: guestbook
